av_awesome_spool_mailer:
    contact_addresses:
        admin:
            address: admin@appventus.com
            name: Administrateur

white_october_swift_mailer_db:
    entity_class: AppVentus\Awesome\SpoolMailerBundle\Entity\Mail
