front_template_app:
    resource: "@FrontTemplateBundle/Controller/"
    type:     annotation
    prefix:   /front/template

front_app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /front/app

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

VictoireCoreBundle:
    resource: .
    type: victoire_i18n
